set xlabel 'generation'
set ylabel 'fitness'
set terminal png large size 750,500
set style line 1 lt 1 lw 3
set style line 2 lt 2 lw 3
set style line 3 lt 3 lw 3
set style line 4 lt 4 lw 3
set style line 5 lt 5 lw 3
set style line 6 lt 6 lw 3
set style line 7 lt 7 lw 3
set style line 8 lt 8 lw 3
set style line 9 lt 9 lw 3
set style line 10 lt 1 lw 1
set style line 11 lt 2 lw 1
set style line 12 lt 3 lw 1
set style line 13 lt 4 lw 1
set style line 14 lt 5 lw 1
set style line 15 lt 6 lw 1
set style line 16 lt 7 lw 1
set style line 17 lt 8 lw 1
set style line 18 lt 9 lw 1

set output "graph_onemax_two/graph_onemax_two000_fitness.png"
set title 'OneMax Two Peaks (k: 0.1, PopSize: 10)'
plot "graph_onemax_two/graph_onemax_two0_fitness.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two1_fitness.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two2_fitness.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two3_fitness.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two4_fitness.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two5_fitness.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two6_fitness.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two7_fitness.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8

set output "graph_onemax_two/graph_onemax_two001_fitness.png"
set title 'OneMax Two Peaks (Exact Random Distribution, k: 0.1, PopSize: 10)'
plot "graph_onemax_two/graph_onemax_two9_fitness.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two10_fitness.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two11_fitness.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two12_fitness.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two13_fitness.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two14_fitness.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two15_fitness.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two16_fitness.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8

set output "graph_onemax_two/graph_onemax_two002_fitness.png"
set title 'OneMax Two Peaks (k: 0.4, PopSize: 10)'
plot "graph_onemax_two/graph_onemax_two18_fitness.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two19_fitness.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two20_fitness.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two21_fitness.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two22_fitness.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two23_fitness.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two24_fitness.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two25_fitness.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8

set output "graph_onemax_two/graph_onemax_two003_fitness.png"
set title 'OneMax Two Peaks (Exact Random Distribution, k: 0.4, PopSize: 10)'
plot "graph_onemax_two/graph_onemax_two27_fitness.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two28_fitness.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two29_fitness.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two30_fitness.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two31_fitness.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two32_fitness.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two33_fitness.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two34_fitness.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8

set output "graph_onemax_two/graph_onemax_two004_fitness.png"
set title 'OneMax Two Peaks (k: 0.7, PopSize: 10)'
plot "graph_onemax_two/graph_onemax_two36_fitness.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two37_fitness.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two38_fitness.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two39_fitness.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two40_fitness.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two41_fitness.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two42_fitness.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two43_fitness.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8

set output "graph_onemax_two/graph_onemax_two005_fitness.png"
set title 'OneMax Two Peaks (Exact Random Distribution, k: 0.7, PopSize: 10)'
plot "graph_onemax_two/graph_onemax_two45_fitness.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two46_fitness.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two47_fitness.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two48_fitness.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two49_fitness.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two50_fitness.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two51_fitness.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two52_fitness.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8

set output "graph_onemax_two/graph_onemax_two006_fitness.png"
set title 'OneMax Two Peaks (k: 0.1, PopSize: 40)'
plot "graph_onemax_two/graph_onemax_two54_fitness.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two55_fitness.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two56_fitness.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two57_fitness.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two58_fitness.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two59_fitness.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two60_fitness.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two61_fitness.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8

set output "graph_onemax_two/graph_onemax_two007_fitness.png"
set title 'OneMax Two Peaks (Exact Random Distribution, k: 0.1, PopSize: 40)'
plot "graph_onemax_two/graph_onemax_two63_fitness.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two64_fitness.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two65_fitness.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two66_fitness.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two67_fitness.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two68_fitness.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two69_fitness.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two70_fitness.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8

set output "graph_onemax_two/graph_onemax_two008_fitness.png"
set title 'OneMax Two Peaks (k: 0.4, PopSize: 40)'
plot "graph_onemax_two/graph_onemax_two72_fitness.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two73_fitness.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two74_fitness.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two75_fitness.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two76_fitness.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two77_fitness.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two78_fitness.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two79_fitness.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8

set output "graph_onemax_two/graph_onemax_two009_fitness.png"
set title 'OneMax Two Peaks (Exact Random Distribution, k: 0.4, PopSize: 40)'
plot "graph_onemax_two/graph_onemax_two81_fitness.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two82_fitness.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two83_fitness.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two84_fitness.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two85_fitness.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two86_fitness.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two87_fitness.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two88_fitness.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8

set output "graph_onemax_two/graph_onemax_two010_fitness.png"
set title 'OneMax Two Peaks (k: 0.7, PopSize: 40)'
plot "graph_onemax_two/graph_onemax_two90_fitness.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two91_fitness.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two92_fitness.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two93_fitness.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two94_fitness.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two95_fitness.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two96_fitness.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two97_fitness.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8

set output "graph_onemax_two/graph_onemax_two011_fitness.png"
set title 'OneMax Two Peaks (Exact Random Distribution, k: 0.7, PopSize: 40)'
plot "graph_onemax_two/graph_onemax_two99_fitness.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two100_fitness.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two101_fitness.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two102_fitness.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two103_fitness.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two104_fitness.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two105_fitness.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two106_fitness.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8

set output "graph_onemax_two/graph_onemax_two012_fitness.png"
set title 'OneMax Two Peaks (k: 0.1, PopSize: 70)'
plot "graph_onemax_two/graph_onemax_two108_fitness.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two109_fitness.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two110_fitness.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two111_fitness.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two112_fitness.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two113_fitness.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two114_fitness.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two115_fitness.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8

set output "graph_onemax_two/graph_onemax_two013_fitness.png"
set title 'OneMax Two Peaks (Exact Random Distribution, k: 0.1, PopSize: 70)'
plot "graph_onemax_two/graph_onemax_two117_fitness.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two118_fitness.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two119_fitness.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two120_fitness.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two121_fitness.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two122_fitness.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two123_fitness.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two124_fitness.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8

set output "graph_onemax_two/graph_onemax_two014_fitness.png"
set title 'OneMax Two Peaks (k: 0.4, PopSize: 70)'
plot "graph_onemax_two/graph_onemax_two126_fitness.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two127_fitness.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two128_fitness.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two129_fitness.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two130_fitness.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two131_fitness.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two132_fitness.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two133_fitness.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8

set output "graph_onemax_two/graph_onemax_two015_fitness.png"
set title 'OneMax Two Peaks (Exact Random Distribution, k: 0.4, PopSize: 70)'
plot "graph_onemax_two/graph_onemax_two135_fitness.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two136_fitness.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two137_fitness.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two138_fitness.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two139_fitness.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two140_fitness.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two141_fitness.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two142_fitness.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8

set output "graph_onemax_two/graph_onemax_two016_fitness.png"
set title 'OneMax Two Peaks (k: 0.7, PopSize: 70)'
plot "graph_onemax_two/graph_onemax_two144_fitness.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two145_fitness.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two146_fitness.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two147_fitness.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two148_fitness.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two149_fitness.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two150_fitness.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two151_fitness.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8

set output "graph_onemax_two/graph_onemax_two017_fitness.png"
set title 'OneMax Two Peaks (Exact Random Distribution, k: 0.7, PopSize: 70)'
plot "graph_onemax_two/graph_onemax_two153_fitness.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two154_fitness.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two155_fitness.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two156_fitness.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two157_fitness.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two158_fitness.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two159_fitness.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two160_fitness.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8

set output "graph_onemax_two/graph_onemax_two018_fitness.png"
set title 'OneMax Two Peaks (k: 0.1, PopSize: 100)'
plot "graph_onemax_two/graph_onemax_two162_fitness.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two163_fitness.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two164_fitness.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two165_fitness.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two166_fitness.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two167_fitness.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two168_fitness.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two169_fitness.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8

set output "graph_onemax_two/graph_onemax_two019_fitness.png"
set title 'OneMax Two Peaks (Exact Random Distribution, k: 0.1, PopSize: 100)'
plot "graph_onemax_two/graph_onemax_two171_fitness.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two172_fitness.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two173_fitness.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two174_fitness.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two175_fitness.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two176_fitness.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two177_fitness.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two178_fitness.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8

set output "graph_onemax_two/graph_onemax_two020_fitness.png"
set title 'OneMax Two Peaks (k: 0.4, PopSize: 100)'
plot "graph_onemax_two/graph_onemax_two180_fitness.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two181_fitness.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two182_fitness.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two183_fitness.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two184_fitness.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two185_fitness.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two186_fitness.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two187_fitness.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8

set output "graph_onemax_two/graph_onemax_two021_fitness.png"
set title 'OneMax Two Peaks (Exact Random Distribution, k: 0.4, PopSize: 100)'
plot "graph_onemax_two/graph_onemax_two189_fitness.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two190_fitness.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two191_fitness.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two192_fitness.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two193_fitness.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two194_fitness.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two195_fitness.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two196_fitness.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8

set output "graph_onemax_two/graph_onemax_two022_fitness.png"
set title 'OneMax Two Peaks (k: 0.7, PopSize: 100)'
plot "graph_onemax_two/graph_onemax_two198_fitness.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two199_fitness.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two200_fitness.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two201_fitness.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two202_fitness.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two203_fitness.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two204_fitness.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two205_fitness.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8

set output "graph_onemax_two/graph_onemax_two023_fitness.png"
set title 'OneMax Two Peaks (Exact Random Distribution, k: 0.7, PopSize: 100)'
plot "graph_onemax_two/graph_onemax_two207_fitness.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two208_fitness.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two209_fitness.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two210_fitness.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two211_fitness.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two212_fitness.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two213_fitness.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two214_fitness.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8



set xlabel 'generation'
set ylabel 'diversity p*(1-p)'
set terminal png large size 750,500

set output "graph_onemax_two/graph_onemax_two000_diversity.png"
set title 'OneMax Two Peaks (k: 0.1, PopSize: 10)'
plot "graph_onemax_two/graph_onemax_two0_diversity.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two1_diversity.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two2_diversity.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two3_diversity.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two4_diversity.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two5_diversity.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two6_diversity.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two7_diversity.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8, "graph_onemax_two/graph_onemax_two8_diversity.gnp" ti "(1 - 1/N) loss / generation" with lines ls 9

set output "graph_onemax_two/graph_onemax_two001_diversity.png"
set title 'OneMax Two Peaks (Exact Random Distribution, k: 0.1, PopSize: 10)'
plot "graph_onemax_two/graph_onemax_two9_diversity.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two10_diversity.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two11_diversity.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two12_diversity.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two13_diversity.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two14_diversity.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two15_diversity.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two16_diversity.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8, "graph_onemax_two/graph_onemax_two17_diversity.gnp" ti "(1 - 1/N) loss / generation" with lines ls 9

set output "graph_onemax_two/graph_onemax_two002_diversity.png"
set title 'OneMax Two Peaks (k: 0.4, PopSize: 10)'
plot "graph_onemax_two/graph_onemax_two18_diversity.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two19_diversity.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two20_diversity.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two21_diversity.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two22_diversity.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two23_diversity.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two24_diversity.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two25_diversity.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8, "graph_onemax_two/graph_onemax_two26_diversity.gnp" ti "(1 - 1/N) loss / generation" with lines ls 9

set output "graph_onemax_two/graph_onemax_two003_diversity.png"
set title 'OneMax Two Peaks (Exact Random Distribution, k: 0.4, PopSize: 10)'
plot "graph_onemax_two/graph_onemax_two27_diversity.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two28_diversity.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two29_diversity.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two30_diversity.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two31_diversity.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two32_diversity.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two33_diversity.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two34_diversity.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8, "graph_onemax_two/graph_onemax_two35_diversity.gnp" ti "(1 - 1/N) loss / generation" with lines ls 9

set output "graph_onemax_two/graph_onemax_two004_diversity.png"
set title 'OneMax Two Peaks (k: 0.7, PopSize: 10)'
plot "graph_onemax_two/graph_onemax_two36_diversity.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two37_diversity.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two38_diversity.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two39_diversity.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two40_diversity.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two41_diversity.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two42_diversity.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two43_diversity.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8, "graph_onemax_two/graph_onemax_two44_diversity.gnp" ti "(1 - 1/N) loss / generation" with lines ls 9

set output "graph_onemax_two/graph_onemax_two005_diversity.png"
set title 'OneMax Two Peaks (Exact Random Distribution, k: 0.7, PopSize: 10)'
plot "graph_onemax_two/graph_onemax_two45_diversity.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two46_diversity.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two47_diversity.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two48_diversity.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two49_diversity.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two50_diversity.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two51_diversity.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two52_diversity.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8, "graph_onemax_two/graph_onemax_two53_diversity.gnp" ti "(1 - 1/N) loss / generation" with lines ls 9

set output "graph_onemax_two/graph_onemax_two006_diversity.png"
set title 'OneMax Two Peaks (k: 0.1, PopSize: 40)'
plot "graph_onemax_two/graph_onemax_two54_diversity.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two55_diversity.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two56_diversity.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two57_diversity.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two58_diversity.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two59_diversity.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two60_diversity.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two61_diversity.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8, "graph_onemax_two/graph_onemax_two62_diversity.gnp" ti "(1 - 1/N) loss / generation" with lines ls 9

set output "graph_onemax_two/graph_onemax_two007_diversity.png"
set title 'OneMax Two Peaks (Exact Random Distribution, k: 0.1, PopSize: 40)'
plot "graph_onemax_two/graph_onemax_two63_diversity.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two64_diversity.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two65_diversity.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two66_diversity.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two67_diversity.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two68_diversity.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two69_diversity.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two70_diversity.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8, "graph_onemax_two/graph_onemax_two71_diversity.gnp" ti "(1 - 1/N) loss / generation" with lines ls 9

set output "graph_onemax_two/graph_onemax_two008_diversity.png"
set title 'OneMax Two Peaks (k: 0.4, PopSize: 40)'
plot "graph_onemax_two/graph_onemax_two72_diversity.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two73_diversity.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two74_diversity.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two75_diversity.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two76_diversity.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two77_diversity.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two78_diversity.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two79_diversity.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8, "graph_onemax_two/graph_onemax_two80_diversity.gnp" ti "(1 - 1/N) loss / generation" with lines ls 9

set output "graph_onemax_two/graph_onemax_two009_diversity.png"
set title 'OneMax Two Peaks (Exact Random Distribution, k: 0.4, PopSize: 40)'
plot "graph_onemax_two/graph_onemax_two81_diversity.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two82_diversity.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two83_diversity.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two84_diversity.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two85_diversity.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two86_diversity.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two87_diversity.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two88_diversity.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8, "graph_onemax_two/graph_onemax_two89_diversity.gnp" ti "(1 - 1/N) loss / generation" with lines ls 9

set output "graph_onemax_two/graph_onemax_two010_diversity.png"
set title 'OneMax Two Peaks (k: 0.7, PopSize: 40)'
plot "graph_onemax_two/graph_onemax_two90_diversity.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two91_diversity.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two92_diversity.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two93_diversity.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two94_diversity.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two95_diversity.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two96_diversity.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two97_diversity.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8, "graph_onemax_two/graph_onemax_two98_diversity.gnp" ti "(1 - 1/N) loss / generation" with lines ls 9

set output "graph_onemax_two/graph_onemax_two011_diversity.png"
set title 'OneMax Two Peaks (Exact Random Distribution, k: 0.7, PopSize: 40)'
plot "graph_onemax_two/graph_onemax_two99_diversity.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two100_diversity.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two101_diversity.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two102_diversity.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two103_diversity.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two104_diversity.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two105_diversity.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two106_diversity.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8, "graph_onemax_two/graph_onemax_two107_diversity.gnp" ti "(1 - 1/N) loss / generation" with lines ls 9

set output "graph_onemax_two/graph_onemax_two012_diversity.png"
set title 'OneMax Two Peaks (k: 0.1, PopSize: 70)'
plot "graph_onemax_two/graph_onemax_two108_diversity.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two109_diversity.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two110_diversity.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two111_diversity.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two112_diversity.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two113_diversity.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two114_diversity.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two115_diversity.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8, "graph_onemax_two/graph_onemax_two116_diversity.gnp" ti "(1 - 1/N) loss / generation" with lines ls 9

set output "graph_onemax_two/graph_onemax_two013_diversity.png"
set title 'OneMax Two Peaks (Exact Random Distribution, k: 0.1, PopSize: 70)'
plot "graph_onemax_two/graph_onemax_two117_diversity.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two118_diversity.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two119_diversity.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two120_diversity.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two121_diversity.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two122_diversity.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two123_diversity.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two124_diversity.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8, "graph_onemax_two/graph_onemax_two125_diversity.gnp" ti "(1 - 1/N) loss / generation" with lines ls 9

set output "graph_onemax_two/graph_onemax_two014_diversity.png"
set title 'OneMax Two Peaks (k: 0.4, PopSize: 70)'
plot "graph_onemax_two/graph_onemax_two126_diversity.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two127_diversity.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two128_diversity.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two129_diversity.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two130_diversity.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two131_diversity.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two132_diversity.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two133_diversity.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8, "graph_onemax_two/graph_onemax_two134_diversity.gnp" ti "(1 - 1/N) loss / generation" with lines ls 9

set output "graph_onemax_two/graph_onemax_two015_diversity.png"
set title 'OneMax Two Peaks (Exact Random Distribution, k: 0.4, PopSize: 70)'
plot "graph_onemax_two/graph_onemax_two135_diversity.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two136_diversity.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two137_diversity.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two138_diversity.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two139_diversity.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two140_diversity.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two141_diversity.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two142_diversity.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8, "graph_onemax_two/graph_onemax_two143_diversity.gnp" ti "(1 - 1/N) loss / generation" with lines ls 9

set output "graph_onemax_two/graph_onemax_two016_diversity.png"
set title 'OneMax Two Peaks (k: 0.7, PopSize: 70)'
plot "graph_onemax_two/graph_onemax_two144_diversity.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two145_diversity.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two146_diversity.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two147_diversity.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two148_diversity.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two149_diversity.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two150_diversity.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two151_diversity.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8, "graph_onemax_two/graph_onemax_two152_diversity.gnp" ti "(1 - 1/N) loss / generation" with lines ls 9

set output "graph_onemax_two/graph_onemax_two017_diversity.png"
set title 'OneMax Two Peaks (Exact Random Distribution, k: 0.7, PopSize: 70)'
plot "graph_onemax_two/graph_onemax_two153_diversity.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two154_diversity.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two155_diversity.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two156_diversity.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two157_diversity.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two158_diversity.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two159_diversity.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two160_diversity.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8, "graph_onemax_two/graph_onemax_two161_diversity.gnp" ti "(1 - 1/N) loss / generation" with lines ls 9

set output "graph_onemax_two/graph_onemax_two018_diversity.png"
set title 'OneMax Two Peaks (k: 0.1, PopSize: 100)'
plot "graph_onemax_two/graph_onemax_two162_diversity.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two163_diversity.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two164_diversity.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two165_diversity.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two166_diversity.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two167_diversity.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two168_diversity.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two169_diversity.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8, "graph_onemax_two/graph_onemax_two170_diversity.gnp" ti "(1 - 1/N) loss / generation" with lines ls 9

set output "graph_onemax_two/graph_onemax_two019_diversity.png"
set title 'OneMax Two Peaks (Exact Random Distribution, k: 0.1, PopSize: 100)'
plot "graph_onemax_two/graph_onemax_two171_diversity.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two172_diversity.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two173_diversity.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two174_diversity.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two175_diversity.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two176_diversity.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two177_diversity.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two178_diversity.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8, "graph_onemax_two/graph_onemax_two179_diversity.gnp" ti "(1 - 1/N) loss / generation" with lines ls 9

set output "graph_onemax_two/graph_onemax_two020_diversity.png"
set title 'OneMax Two Peaks (k: 0.4, PopSize: 100)'
plot "graph_onemax_two/graph_onemax_two180_diversity.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two181_diversity.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two182_diversity.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two183_diversity.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two184_diversity.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two185_diversity.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two186_diversity.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two187_diversity.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8, "graph_onemax_two/graph_onemax_two188_diversity.gnp" ti "(1 - 1/N) loss / generation" with lines ls 9

set output "graph_onemax_two/graph_onemax_two021_diversity.png"
set title 'OneMax Two Peaks (Exact Random Distribution, k: 0.4, PopSize: 100)'
plot "graph_onemax_two/graph_onemax_two189_diversity.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two190_diversity.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two191_diversity.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two192_diversity.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two193_diversity.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two194_diversity.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two195_diversity.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two196_diversity.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8, "graph_onemax_two/graph_onemax_two197_diversity.gnp" ti "(1 - 1/N) loss / generation" with lines ls 9

set output "graph_onemax_two/graph_onemax_two022_diversity.png"
set title 'OneMax Two Peaks (k: 0.7, PopSize: 100)'
plot "graph_onemax_two/graph_onemax_two198_diversity.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two199_diversity.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two200_diversity.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two201_diversity.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two202_diversity.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two203_diversity.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two204_diversity.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two205_diversity.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8, "graph_onemax_two/graph_onemax_two206_diversity.gnp" ti "(1 - 1/N) loss / generation" with lines ls 9

set output "graph_onemax_two/graph_onemax_two023_diversity.png"
set title 'OneMax Two Peaks (Exact Random Distribution, k: 0.7, PopSize: 100)'
plot "graph_onemax_two/graph_onemax_two207_diversity.gnp" ti "No correction" with lines ls 1, "graph_onemax_two/graph_onemax_two208_diversity.gnp" ti "No correction + bounded" with lines ls 2, "graph_onemax_two/graph_onemax_two209_diversity.gnp" ti "Laplace correction" with lines ls 3, "graph_onemax_two/graph_onemax_two210_diversity.gnp" ti "Laplace remember correction" with lines ls 4, "graph_onemax_two/graph_onemax_two211_diversity.gnp" ti "Corrected distribution" with lines ls 5, "graph_onemax_two/graph_onemax_two212_diversity.gnp" ti "Corrected distribution + bounded" with lines ls 6, "graph_onemax_two/graph_onemax_two213_diversity.gnp" ti "Corrected distribution + Laplace" with lines ls 7, "graph_onemax_two/graph_onemax_two214_diversity.gnp" ti "Corrected distribution + r. Laplace" with lines ls 8, "graph_onemax_two/graph_onemax_two215_diversity.gnp" ti "(1 - 1/N) loss / generation" with lines ls 9



